name: Publish

on:
    workflow_dispatch: # Manual triggering of workflow

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: schroedinger-hat
        run: npm install

      - name: Publish
        working-directory: schroedinger-hat
        env:
          SPOTIFY_EMAIL: ${{ secrets.SPOTIFY_EMAIL }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
          SERMON_PLAYLIST_ID: ${{ secrets.SERMON_PLAYLIST_ID }}
          SAVE_AS_DRAFT: true
          LOAD_THUMBNAIL: true
          URL_IN_DESCRIPTION: false
        run: npm start